### ISSUE TITLE
resetting lorbit for ispin=1?

### ISSUE THREAD

**Issue by prtkm** [jkitchin/vasp#22]
On this line, https://github.com/jkitchin/vasp/blob/master/vasp/setters.py#L76 you seem to reset lorbit to None if ispin=1. Is there any particular reason why you do this?

Say I want to do a non-spin polarized calculation, and have lorbit=10, to get the atom projected dos, this gets reset to None. It also raises an assertion error in validate later.

**Comment by jkitchin** [comment]
hm. If that is legitimate, we should probably change the setter and validator. At some point I must have thought what you suggested was not legit.

**Comment by prtkm** [comment]
Ok great. I'll submit a PR soon.
