### ISSUE TITLE
Force setting lwave...

### ISSUE THREAD

**Issue by prtkm** [jkitchin/vasp#23]
lwave seems to be always set to true if nsw > 0 https://github.com/jkitchin/vasp/blob/master/vasp/setters.py#L167. 

This happens even when I explicitly set lwave to False when creating the calculator. This is problematic because if you run 100s of ionic relaxations, you end up filling 100s of GBs of disk space. In my case I eventually exceed my storage quota, and all my jobs die :(

**Comment by jkitchin** [comment]
You might try this in your script:

@monkeypatch_class(vasp.Vasp)
def set_nsw_dict(self, val):
    return {}

I am not sure what the best path here is. This set as a default to help with restarts if the jobs get killed. i am not totally committed to it though.

**Comment by prtkm** [comment]
Maybe we can have a set_lwave function that only sets lwave if it doesn't
already exist in calc.parameters

**Comment by jkitchin** [comment]
We should probably eliminate the logic on lwave, and just make users set it to True if they want it. I removed this in 11d2a54.

**Comment by prtkm** [comment]
Looks good
