### ISSUE TITLE
ZBRENT bracketing errors

### ISSUE THREAD

**Issue by prtkm** [jkitchin/vasp#3]
Sometimes during conjugate gradient optimizations I get this error (these are the last few lines of my vasp stdout file.

```
       N       E                     dE             d eps       ncg     rms          rms(c)
DAV:   1    -0.808978395638E+03   -0.10606E-05   -0.49230E-05  2080   0.160E-02    0.333E-02
RMM:   2    -0.808978711288E+03   -0.31565E-03   -0.12893E-04  1630   0.152E-02    0.298E-01
RMM:   3    -0.808978163978E+03    0.54731E-03   -0.10917E-04  1576   0.167E-02    0.806E-02
RMM:   4    -0.808978368321E+03   -0.20434E-03   -0.33170E-05  1336   0.843E-03    0.444E-02
RMM:   5    -0.808978372128E+03   -0.38079E-05   -0.72285E-06   961   0.454E-03
  59 F= -.80897837E+03 E0= -.80897978E+03  d E =-.204339E-02  mag=    -0.3409
 curvature:   0.00 expect dE=-0.247E-08 dE for cont linesearch -0.117E-08
 ZBRENT: interpolating
 opt :   0.6785  next Energy=  -808.979501 (dE=-0.317E-02)
 bond charge predicted
       N       E                     dE             d eps       ncg     rms          rms(c)
DAV:   1    -0.808978358854E+03    0.94668E-05   -0.10023E-05  2032   0.697E-03    0.182E-02
RMM:   2    -0.808978312836E+03    0.46018E-04   -0.97341E-06  1244   0.486E-03
  60 F= -.80897831E+03 E0= -.80898022E+03  d E =-.198409E-02  mag=    -0.3378
 curvature:   0.00 expect dE=-0.405E-09 dE for cont linesearch -0.143E-09
 ZBRENT: interpolating
 opt :   0.6785  next Energy=  -808.979501 (dE=-0.317E-02)
 bond charge predicted
       N       E                     dE             d eps       ncg     rms          rms(c)
DAV:   1    -0.808978272998E+03    0.85855E-04   -0.12172E-05  2032   0.996E-03    0.246E-02
RMM:   2    -0.808978269206E+03    0.37918E-05   -0.29084E-05  1345   0.590E-03
  61 F= -.80897827E+03 E0= -.80898068E+03  d E =-.194046E-02  mag=    -0.3340
 curvature:   0.00 expect dE=-0.338E-09 dE for cont linesearch -0.426E-10
 ZBRENT:  can not reach accuracy
 opt :   0.0000  next Energy=     0.000000 (dE= 0.809E+03)
 bond charge predicted
       N       E                     dE             d eps       ncg     rms          rms(c)
DAV:   1    -0.808977102563E+03    0.11704E-02   -0.10614E-01  3392   0.465E-01    0.338E-01
RMM:   2    -0.809064633783E+03   -0.87531E-01   -0.17818E-02  3195   0.104E-01    0.746E+00
RMM:   3    -0.808928314960E+03    0.13632E+00   -0.17136E-02  2844   0.122E-01    0.621E-01
RMM:   4    -0.808973971408E+03   -0.45656E-01   -0.36113E-03  2723   0.868E-02    0.422E-01
RMM:   5    -0.808976894323E+03   -0.29229E-02   -0.60123E-04  2128   0.386E-02    0.241E-01
RMM:   6    -0.808976679739E+03    0.21458E-03   -0.11445E-04  1662   0.160E-02    0.243E-01
RMM:   7    -0.808976527328E+03    0.15241E-03   -0.10336E-04  1656   0.154E-02    0.236E-01
RMM:   8    -0.808976418689E+03    0.10864E-03   -0.86241E-05  1593   0.155E-02    0.179E-01
RMM:   9    -0.808976445212E+03   -0.26523E-04   -0.54527E-05  1600   0.139E-02
  62 F= -.80897645E+03 E0= -.80897894E+03  d E =-.116469E-03  mag=    -0.3177
 curvature:   0.00 expect dE= 0.000E+00 dE for cont linesearch  0.000E+00
 ZBRENT: fatal error in bracketing
     please rerun with smaller EDIFF, or copy CONTCAR
     to POSCAR and continue
```

This is a special case of VaspNotFinished (http://cms.mpi.univie.ac.at/vasp-forum/viewtopic.php?t=1856). Usually I can get it to work, by deleting the OUTCAR, and resubmitting the job from CONTCAR. One could even change ibrion if required. In jasp, I would do something like below, so the next time I ran it, the job would be automatically resubmitted.

``` python
    with open('OUTCAR') as f:
        lines = f.readlines()

    if 'Voluntary context switches' not in lines[-1]:
        try:
            # -5 line of output contains Zbrent message.
            if 'ZBRENT: fatal error in bracketing' in output[-5]:
                message = ['Zbrent Error in: \n {0} \n'.format(os.getcwd()),
                           'OUTCAR has been deleted.\n', 
                           'Please run your script again to restart from CONTCAR']
                os.unlink('OUTCAR')
                raise VaspZbrentError(''.join(message))
        except IndexError:
            pass            
        output += ['Last 20 lines of OUTCAR:\n']
        output += lines[-20:]
        output += ['=' * 66]
        raise VaspNotFinished(''.join(output))
```

It might be useful to have it in the new vasp.py.

**Comment by jboes** [comment]
This is a more specific instance of the general case where an ionic step has been completed, but the system has not yet converged. The solution for both cases is often the same, but now always.

Rather than adding specific fixes to the core code you should consider creating a branch on your personal fork which passes a personalized exception handler which contains your function. In Jasp, this would not only apply your personalized fix, but also re-initiate the context manager meaning the block would not need to be run again to restart! 

I'm not sure this functions the same in vasp, since the context manager no longer exists. However, I believe the functionality of the exception handler is the same. John can confirm or deny.

**Comment by prtkm** [comment]
It's true it is a more specific case of an unconverged ionic calculation, but it is something that is possible to catch and fix pretty easily. I haven't yet tried the personalized exception handlers in jasp, I'm just waiting for vasp.py to become stable enough so I can make the switch. :) 

Btw, which function handles restarts in vasp?

**Comment by jkitchin** [comment]
what do you mean by a restart?

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
Things like if a calculation didn't reach convergence after nsw steps or if a job died for some reason, and we want to resubmit the job.

**Comment by jkitchin** [comment]
That would be done in https://github.com/jkitchin/vasp/blob/master/vasp/vasp_core.py#L24

Maybe as easy as doing some cleanup and saying: self.update()

This is the default function used for exception_handler. But, you can use your own in __init__ (https://github.com/jkitchin/vasp/blob/master/vasp/vasp_core.py#L137).

When a good default restart behavior exists we will add it to the default function.

I haven't decided if the exception_handler should be set in vasprc or in init (like it is now)

**Comment by prtkm** [comment]
I think vaspy automatically recognizes and addresses this issue by restarting the job.
