### ISSUE TITLE
vaspy and python3

### ISSUE THREAD

**Issue by prtkm** [jkitchin/vasp#33]
Hi John,

Have you tried running vaspy with python3? I seem to be getting this error on the initial import, but am not sure why that is. Any ideas?

>>> from vasp import Vasp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/afs/crc.nd.edu/user/p/pmehta1/vasp/vasp/__init__.py", line 1, in <module>
    from vasp import Vasp
ImportError: cannot import name 'Vasp'

**Comment by prtkm** [comment]
I think that the imports need to be changed to relative imports. ```2to3 -w *.py``` apparently tries to fix all of these, but I am still left with some incompatibilites.

**Comment by prtkm** [comment]
Commits https://github.com/prtkm/vasp/commit/18a3942d9eb107a038d639bf21dbb08c32b7ef37 and https://github.com/prtkm/vasp/commit/d0d122a3c4492134e105a49e54cf11125b68a10f is what I had to do to get the imports to work with python3. These mostly contain automatic fixes made by ```2to3```. I haven't tried running any calculations yet.

**Comment by prtkm** [comment]
I think most things are working with python3 now. The recent commits on https://github.com/prtkm/vasp/commits/SGE-py3 deal with bytes vs str issues, and fixes the exception handler and also include a fix to deal with a recent change in ase to raise PropertyNotImplementedErrors when something is not computed.

Sorry about so many comments on this thread!

**Comment by jkitchin** [comment]
Thanks for the links to the fixes. I probably won't try to go to python3 until Jake graduates. He is eager to switch though. The main thing that was holding me back was the ase-gui. Are you using that, and if so does it work well?

**Comment by prtkm** [comment]
The gui works, and does most of the things I want, though it is less prettyfrom what it used to be. Some of the options I don't use very often (for example creating a slab inside the gui) are not functional yet. The only issue is when I do ```view(atoms)``` with a Vasp calculator attached, it doesn't seem to work right now. I think this is related to a byte/string encoding issue with one of the results in the calculator. I haven't tracked it down yet, but I don't think it should be very hard to fix.

In the dev version of ase, I think that both the python2 and python3 guis use tkinter now. In ase versions from say a month ago, everything still seems to work with python3, with the workaround that the view function uses the python2 pygtk gui.

**Comment by jboes** [comment]
Thanks for patching this up Prateek. I have a branch with the required commits (Minus the Bader changes) and will try it out for a while and see if there are any issues.

**Comment by jboes** [comment]
A few more or Prateek's commits are required to make vaspy functional in python 3:
prtkm@6a499ad
prtkm@6762eed

In line 185 of ase/io/trajectoy.py in ase version 3.13.0, adding 'charges' to the list of properties converted to lists will restore visualization functionality to atoms objects with attached calculators:

```python
                if x is not None:
                    if prop in ['stress', 'dipole']:
                        x = x.tolist()
                    c.write(prop, x)
```

to

```python
                if x is not None:
                    if prop in ['stress', 'dipole', 'charges']:
                        x = x.tolist()
                    c.write(prop, x)
```
