### ISSUE TITLE
Updating atoms in a cloned calculation?

### ISSUE THREAD

**Issue by MAHines** [jkitchin/vasp#41]
How do you update the atoms in a cloned calculation? For example, I would like to clone a relaxed structure, fix the positions of most of the atoms (_e.g.,_ the slab), then calculate the vibrational spectrum of the remaining atoms (_e.g.,_ the adsorbates). I have tried a number of different things, but vasp never writes a new, updated POSCAR file, instead it uses the original CONTCAR from the previous calculation. 

For example, this does not work:

    from vasp import Vasp
    from ase.constraints import FixAtoms

    calc = Vasp("oldCalc")
    calc.clone("newCalc")

    # Freeze all of the atoms in the slab
    slab = calc.get_atoms()
    inSlab = []
    for atom in slab:
        inSlab.append(atom.index)
    theConstraints = FixAtoms(indices = inSlab)
    slab.set_constraint(theConstraints)

    # Update the calculator with the constrained slab
    calc.atoms = slab

    name = 'vasp.executable.serial'
    calc.VASPRC[name] = 'runvasp.py'
    calc.set(nsw = 5)   # This just forces a recalculation
    
    calc.calculate()    # This initiates a calculation on the _unconstrained_ slab / original CONTCAR

Thanks,

Melissa

**Comment by jkitchin** [comment]
hm. I would have thought something like the example in 5.9.1 near this
http://kitchingroup.cheme.cmu.edu/dft-book/dft.html#orgheadline45 would
do what you want.

You might also try calc.write_input() after you modify it to see if that
generates a new POSCAR.

It might be necessary to delete the CONTCAR though, if it is only the
POSCAR that is updated.

Unfortunately, I am busy tomorrow preparing to move for a sabbatical
that starts Wed, and then I will be busy settling my family and getting
started for the next three weeks at least. I will probably not have time
to look more into it before then.

@jboes @prtkm have you done anything like this before?

**Comment by MAHines** [comment]
Thank you for the rapid reply. The code that you reference would do what I want except that I need to freeze a lot of the atoms to avoid wasting resources.

I tried the calc.write_input() approach that you mention. What is weird is that this command rewrites the POSCAR, but it uses the old slab not the updated slab. (I did examine calc.atoms in Python, and I can see that the atoms are indeed constrained.) I also tried write_vasp('POSCAR', calc.atoms_sorted, symbol_count=calc.symbol_count), which also writes the wrong POSCAR.

Thanks for your help and enjoy your sabbatical.

**Comment by prtkm** [comment]
As far as I remember, when a calculator method is called it re-initializes the calculation from the atoms that are already present in CONTCAR file the directory. This is probably to ensure the atoms are always up to date with what is in the directory (say when you run the script that submits the calculation again). I don't think cloning and then updating the atoms is allowed / implemented at this moment.

As a workaround, I would do calc.get_atoms() from the old calculation, and then start a new calculation by setting the input params again. This approach is not ideal if you want to read the WAVECARs / CHGCARs and use those as a starting point for the new calculations (I usually don't write them anyway). 

The other option would be to delete the CONTCAR from calc.directory like John said before submitting the job. This preserves the WAVECAR and CHGCAR files, but requires you to add a couple of extra lines.

**Comment by MAHines** [comment]
Thanks to you both for your help. The problem is that I was only updating calc.atoms, when I should have also been updating calc.atoms_sorted. Apparently, the latter is used for writing the POSCAR. The following code works:

    from vasp import Vasp
    from ase.constraints import FixAtoms

    calc = Vasp("oldCalc")
    calc.clone("newCalc")

    # Freeze all of the atoms in the slab
    slab = calc.get_atoms()
    inSlab = []
    for atom in slab:
        inSlab.append(atom.index)

    theConstraints = FixAtoms(indices = inSlab)
    slab.set_constraint(theConstraints)

    # Update the calculator with the constrained slab
    calc.atoms = slab
    calc.atoms_sorted = slab[calc.sort]     # This is the key line

    name = 'vasp.executable.serial'
    calc.VASPRC[name] = 'runvasp.py'
    calc.set(nsw = 5)   # This just forces a recalculation

    calc.calculate()    # This initiates a calculation on the _unconstrained_ slab / original CONTCAR

**Comment by jkitchin** [comment]
Thanks for the solution. It sounds like we need a set_atoms function to do that for us, or a setter function for the atoms attribute.
