### ISSUE TITLE
QXcbConnection

### ISSUE THREAD

**Issue by jwz-ecust** [jkitchin/vasp#43]
In [1]: from vasp import Vasp

In [2]: QXcbConnection: Could not connect to display
Aborted (core dumped)

**Comment by yqshao** [comment]
Try `export QT_QPA_PLATFORM=offscreen` ( before running ipython ),
or switching the backbend if you're using jupyter?

**Comment by jwz-ecust** [comment]
import os 
os.encironment[‘QT_QPA_PLATFORM’]=‘offscreen’
