### ISSUE TITLE
brach python3 : write_incar() function treat string a list 

### ISSUE THREAD

**Issue by imusa007** [jkitchin/vasp#57]
Newbie alert!
Brach: python3 produce INCAR like 

 ENCUT = 500
 PREC = A c c u r a t e  
 LWAVE = .FALSE.
 ISTART = 0
 EDIFF = 1e-06
 ALGO = V e r y F a s t

which should be PREC=Accurate and ALGO=VeryFast

changing 
'''# elif isinstance(val, list) or isinstance(val, tuple):
            elif hasattr(val, '__iter__'):
                val = ' '.join(str(x) for x in val)
            f.write(f'{key} = {val}\n')'''

To
''' 
elif isinstance(val, list) or isinstance(val, tuple):
                val = ' '.join(str(x) for x in val)
            f.write(f'{key} = {val}\n')'''

seems to solve the problem.

**Comment by jkitchin** [comment]
That is indeed a bug, thanks for reporting it. I think I have fixed it in the commit above. Sorry it took so long!
