### ISSUE TITLE
Error: cannot import name 'Vasp' from 'vasp' 

### ISSUE THREAD

**Issue by frankNiessen** [jkitchin/vasp#59]
Hi, 

I am sure I have done something wrong here, but I cannot seem to get the vasp library to run. I have defined the python and general paths as well as the potential directory. 

when trying to import vasp `import  vasp` I get the error  

> File "~/OneDrive/pyCharm/VASPjobs/jupyterNotebooks/test.py", line 1, in <module>
    import vasp
  File "~/pycharm-2020.2.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "~/gitRepos/vasp_kitchin/vasp/__init__.py", line 1, in <module>
    from vasp import Vasp
ImportError: cannot import name 'Vasp' from 'vasp' (~/gitRepos/vasp_kitchin/vasp/__init__.py) <

I don't really know why this is happening, but to me it looks like the error is caused by a circular refrence? 

- `import vasp` calls __init__.py
- __init__.py calls vasp.py
- vasp.py calls vasp_core.py
- vasp_core.py  calls vasp.py

I am sure that I got it wrong, otherwise this would be a serious issue, but anyways, I cannot get the library to run and would be happy for any input.

In my .bashrc I defined: 

export PYTHONPATH=~/gitRepos/vasp_kitchin:$PYTHONPATH
export JUPYTER_PATH=~/gitRepos/vasp_kitchin:$JUPYTER_PATH
export PATH=~/gitRepos/vasp_kitchin/bin:$PATH
export VASP_PP_PATH=~/VASP_5_4_4/mypps

I run Python 3.7 and tested this within Jupyter and PyCharm.

**Comment by jkitchin** [comment]
I think you need to checkout the python3 branch of this code. The master branch may be a Python2 branch. 

You can get the zip for this at:
https://github.com/jkitchin/vasp/archive/refs/heads/python3.zip

this at least imports for me.

We don't use this code a lot. It has turned out to be difficult to maintain.

**Comment by frankNiessen** [comment]
Thank you for the reply. It seems to help with the error. I however end up running into the next one when trying the code in conjunction with ASE 3.20.1. You are right that it is difficult to maintain and I will therefore pursue a different solution for now.

**Comment by jkitchin** [comment]
I don't think this vasp library works with the newest ase. it probably only works from 3.18 or so.

**Comment by chenweiguang82** [comment]
> I don't think this vasp library works with the newest ase. it probably only works from 3.18 or so.

It would be nice to integrate this module into ase. Ase's Vasp module is indeed older and less functional.

**Comment by jkitchin** [comment]
This code is probably bit-rotting since we don't use it much anymore.  Probably the era of computing where this was the way to run vasp has passed, and a new design should be considered. It is unlikely to be done by me; we don't really use vasp anymore.
